version: "3"

services:
  app:
    build:
      context: ./01_FLASK_DOCKER
      dockerfile: Dockerfile
    links:
      - "db:mysqldb"
    ports:
      - "80:8080"
    container_name: appcontainer
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./mysqldata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=jewondb
    ports:
      - 3306:3306
    container_name: dbcontainer
# Docker 실행
# - docker-compose run -d
# Docker 로그확인
# - docker-compose logs
# Docker 설정 보기
# - docker-compose config
# Docker 컨테이너에 명령 실행
# - docker-compose exec app /bin/bash
# - 여기서 app은 docker-compose.yml에서 지정한 services 이름
